const categories = [
  // MRO and Capex
  { id: 1, title: "Facility Management" },
  { id: 2, title: "Maintenance Services" },
  { id: 3, title: "Engineering Services" },
  { id: 4, title: "Industrial Supplies" },
  { id: 5, title: "Environment & Safety" },
  { id: 6, title: "Co-manufacturing" },
  { id: 7, title: "Construction" },
  { id: 8, title: "Manufacturing and other equipment" },
  { id: 9, title: "Manufacturing automation & Process Control" },
  { id: 10, title: "HVAC, PTB and other MRO Supplies" },

  // Logistics
  { id: 11, title: "FTL" },
  { id: 12, title: "LTL" },
  { id: 13, title: "Intermodal" },
  { id: 14, title: "Ocean freight" },
  { id: 15, title: "Air freight" },
  { id: 16, title: "Express mail and small packages" },
  { id: 17, title: "3PL/ Warehouse" },
  { id: 18, title: "Distribution" },
  { id: 19, title: "Fleet management" },
  { id: 20, title: "Shipyard Services" },
  { id: 21, title: "Others" },

  // General & Admin
  { id: 22, title: "Temp staffing" },
  { id: 23, title: "Office supplies" },
  { id: 24, title: "HR/ Benefits" },
  { id: 25, title: "Consulting" },
  { id: 26, title: "Legal Services" },
  { id: 27, title: "Tax/Audit Services" },
  { id: 28, title: "Other Professional services" },
  { id: 29, title: "Facilities & Real Estate" },
  { id: 30, title: "Fleet" },
  { id: 31, title: "Relocation" },
  { id: 32, title: "Travel Categories" },
  { id: 33, title: "Meetings & Events" },
  { id: 34, title: "BPO Services" },

  // Packaging
  { id: 35, title: "Corrugated" },
  { id: 36, title: "Pallets" },
  { id: 37, title: "Films, Stretch/ shrink wrap/BOPP" },
  { id: 38, title: "Plastic bottles" },
  { id: 39, title: "Poly bags" },
  { id: 40, title: "Carton Board" },
  { id: 41, title: "Bulk Packaging" },
  { id: 42, title: "Labels" },
  { id: 43, title: "Glass jars /caps" },
  { id: 44, title: "Specialty Packages and packaging innovation" },

  // Marketing
  { id: 45, title: "Market research" },
  { id: 46, title: "Media production/buy" },
  { id: 47, title: "Print and Promotion" },
  { id: 48, title: "Digital Marketing" },
  { id: 49, title: "Creative services" },
  { id: 50, title: "FSI" },
  { id: 51, title: "Website development" },
  { id: 52, title: "Comps" },
  { id: 53, title: "PR & Public Policy" },
  { id: 54, title: "Displays" },
  { id: 55, title: "Call center" },

  // Industrial Manufacturing
  { id: 56, title: "Casting, & Fabrication" },
  { id: 57, title: "Electric Drives, Motors & Gearboxes" },
  { id: 58, title: "Hydraulics & Pneumatics" },
  { id: 59, title: "Mechanical Drives & Transmission" },
  { id: 60, title: "Automation & Control Systems" },
  { id: 61, title: "Relays, Switches, Transformers" },
  { id: 62, title: "Electrical Equipment & Components" },

  // IT & Telecom
  { id: 63, title: "IT hardware" },
  { id: 64, title: "IT software" },
  { id: 65, title: "Maintenance & support" },
  { id: 66, title: "IT consulting" },
  { id: 67, title: "Outsourcing" },
  { id: 68, title: "Telecom hardware" },
  { id: 69, title: "Telecom data and voice" },
  { id: 70, title: "Digital Marketing platforms" },

  // Chemicals
  { id: 71, title: "Basic & Specialty" },
  { id: 72, title: "Resins" },
  { id: 73, title: "Elastomers" },
  { id: 74, title: "Additives" },
  { id: 75, title: "Pigments" },
  { id: 76, title: "Intermediate" },
  { id: 77, title: "Agrochemicals" },
  { id: 78, title: "Petrochemicals" },
  { id: 79, title: "Fibers" },
  { id: 80, title: "Solvents" },
  { id: 81, title: "Fertilizers" },
  { id: 82, title: "Polymers" },

  // Metals, Mining & Energy
  { id: 83, title: "Metals & Product Forms" },
  { id: 84, title: "Non-Ferrous Metals" },
  { id: 85, title: "Rare Earth Metals" },
  { id: 86, title: "Minerals" },
  { id: 87, title: "Ores" },
  { id: 88, title: "Mining Equipment" },
  { id: 89, title: "Crude Oil" },
  { id: 90, title: "Natural Gas" },
  { id: 91, title: "Electricity" },
  { id: 92, title: "Renewable" },
  { id: 93, title: "Finished Goods Components" },

  // Finance/Banking
  { id: 94, title: "Market research" },
  { id: 95, title: "Print and Promotion" },
  { id: 96, title: "Direct mail Campaigns" },
  { id: 97, title: "Cards & chips" },
  { id: 98, title: "Digital Marketing" },
  { id: 99, title: "Website & App development" },
  { id: 100, title: "PR & Public Policy" },
  { id: 101, title: "Retail Displays" },
  { id: 102, title: "Call center" },
  { id: 103, title: "Buildings Maintenance" },
];

export default categories;
